openapi: 3.0.0
info:
  title: Collecthor API
  version: '2.0'
  contact:
    name: Collecthor BV
    email: info@collecthor.nl
    url: 'https://collecthor.nl'
  description: Public API for the Collecthor Platform
servers:
  - description: Production
    url: 'https://app.collecthor.nl'
paths:
  '/panels/{panelId}/members':
    parameters:
      - schema:
          type: integer
        name: panelId
        in: path
        required: true
        description: 'ID of the panel for which to retrieve members '
    get:
      summary: Retrieve member data
      tags: []
      responses:
        '200':
          description: OK
          headers:
            x-pagination-total-count:
              schema:
                type: integer
            x-pagination-page-count:
              schema:
                type: integer
            x-pagination-current-page:
              schema:
                type: integer
            x-pagination-per-page:
              schema:
                type: integer
            link:
              schema:
                type: string
              description: 'Links to self, next, previous and last pages'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/member.v1.yaml
      operationId: get-panels-panelId-members
      description: 'Returns members in a panel, pagination happens via headers, response types are JSON or CSV'
      parameters:
        - schema:
            type: number
          in: header
          name: x-pagination-per-page
          description: Number of records to return per page
  '/members/{memberId}':
    parameters:
      - schema:
          type: integer
        name: memberId
        in: path
        required: true
    get:
      summary: Retrieve individual member
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/member.v1.yaml
      operationId: get-members-memberId
    patch:
      summary: Partially update Member
      operationId: patch-members-memberId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/member.v1.yaml
      description: |-
        This will update only the given attributes, ignoring other attributes.
        When updating data a recursive merge strategy is used.
    put:
      summary: Update Member
      operationId: put-members-memberId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/member.v1.yaml
      description: |-
        This will update only given attributes, ignoring other attributes.
        When updating data the current data is fully replaced.
  /members:
    post:
      summary: Create member
      operationId: post-members
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/member.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/newmember.v1.yaml
        description: ''
  /rewards:
    post:
      summary: Create a new reward
      operationId: post-rewards
      responses:
        '200':
          description: OK
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
    apiKey:
      name: X-API-Key
      type: apiKey
      in: header
security:
  - bearer: []
  - apiKey: []
