openapi: 3.0.0
info:
  title: Collecthor API
  version: '2.0'
  contact:
    name: Collecthor BV
    email: info@collecthor.nl
    url: 'https://collecthor.nl'
  description: Public API for the Collecthor Platform
servers:
  - url: 'http://localhost:3100'
    description: Stoplight Studio
  - description: Standalone Prism
    url: 'http://localhost:4010'
paths:
  '/panels/{panelId}/members':
    parameters:
      - schema:
          type: integer
        name: panelId
        in: path
        required: true
        description: 'ID of the panel for which to retrieve members '
    get:
      summary: Retrieve member data
      tags: []
      responses:
        '200':
          description: OK
          headers:
            x-pagination-total-count:
              schema:
                type: integer
            x-pagination-page-count:
              schema:
                type: integer
            x-pagination-current-page:
              schema:
                type: integer
            x-pagination-per-page:
              schema:
                type: integer
            link:
              schema:
                type: string
              description: 'Links to self, next, previous and last pages'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/member.v1.yaml
      operationId: get-panels-panelId-members
      description: 'Returns members in a panel, pagination happens via headers, response types are JSON or CSV'
      parameters:
        - schema:
            type: number
          in: header
          name: x-pagination-per-page
          description: Number of records to return per page
  '/members/{memberId}':
    parameters:
      - schema:
          type: integer
        name: memberId
        in: path
        required: true
    get:
      summary: Retrieve individual member
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/member.v1.yaml
      operationId: get-members-memberId
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
    apiKey:
      name: X-API-Key
      type: apiKey
      in: header
security:
  - bearer: []
  - apiKey: []
