openapi: 3.0.0
info:
  title: Response data
  version: '1.0'
  contact:
    name: Collecthor BV
    email: info@collecthor.nl
    url: 'https://collecthor.nl'
  description: Public API for the Collecthor Platform
servers:
  - url: 'http://localhost:3100'
    description: Mock
paths:
  '/data/project/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: The project ID
    get:
      summary: Get response data
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/flatresponseset.v1.yaml
            application/xml:
              schema:
                title: FlatResponseSet
                type: array
                xml:
                  wrapped: true
                  name: responses
                items:
                  $ref: ../models/flatresponsedata.v1.yaml
                description: Set of flattened responses
                x-examples:
                  example-1:
                    value:
                      - id: 15
                        created: '2019-13-10 22:22:00'
                        channel_id: 15

          headers: {}
      parameters: []
      operationId: getProjectData
      description: Retrieve all data from a project as JSON or XML
components:
  schemas: {}
