openapi: 3.0.0
info:
  title: Response data
  version: '1.0'
  contact:
    name: Collecthor BV
    email: info@collecthor.nl
    url: 'https://collecthor.nl'
  description: Public API for the Collecthor Platform
servers:
  - url: 'http://localhost:3100'
    description: Stoplight Studio
  - description: Standalone Prism
    url: 'http://localhost:4010'
paths:
  '/data/project/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: The project ID
    get:
      summary: Get response data
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/flatresponseset.v1.yaml
            application/xml:
              schema:
                $ref: ../models/flatresponseset.v1.yaml
          headers: {}
      parameters:
        - schema:
            type: string
            enum:
              - application/json
              - application/xml
          in: header
          name: Accept
          description: ''
      operationId: getProjectData
      description: Retrieve all data from a project as JSON or XML
components:
  schemas: {}
